# Generated by Django 4.0.2 on 2022-02-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('round', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('playerCard', models.CharField(blank=True, max_length=200, null=True)),
                ('computerCard', models.CharField(blank=True, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
